### ISSUE TITLE
Won't find php by default

### ISSUE THREAD

**Issue by appenz** [5t111111/docker-pocketmine-mp#3]
For me the installer didn't find the installation path for php. Simple fix is to pass the path to start.sh via an environment variable in entrypoint.sh:

PHP_BINARY=/pocketmine/PocketMine-MP/bin/php5/bin/php /pocketmine/PocketMine-MP/start.sh

**Comment by 5t111111** [comment]
Thanks for reporting :smile: 
Fixed in https://github.com/5t111111/docker-pocketmine-mp/commit/541f485d97198bd533472bed73e3155ed2feb561
